### PR TITLE
Allow passing multiple index stores to unused imports tool

### PR DESCRIPTION
**Pull request by pennig**
Useful for operating on per-module index stores. To wit, an unused `import B` in module A will only be marked as unused if the tool can collect the units from A and the USRs from B.

### CODE REVIEW

**Comment by pennig** [comment]
CLA is signed

**Review by keith — APPROVED** [review]
nice thanks!

**Comment by keith** [comment]
you'll have to rebase on https://github.com/lyft/swift-index-store/pull/51 shortly

**Comment by keith** [comment]
thanks!

**Pull request merged**
